# Generated by Django 5.1.7 on 2025-03-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
