# Generated by Django 5.1.7 on 2025-03-18 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='categories/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
